@baseURL = http://localhost:3000

@adopter_Token_Ok = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsImVtYWlsIjoiYWRvcHRlcl90cm9uQGlmcnMuY29tLmJyIiwicm9sZSI6ImFkb3B0ZXIiLCJpYXQiOjE3NTE0MDMyOTEsImV4cCI6MTc1MTQwNjg5MX0.9t69Bxa45dZUmvmFSEhaCveRhCRknNT1B1_EMGjBx-E

@admin_Token_Ok = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsImVtYWlsIjoiYWRtaW4xQGlmcnMuY29tLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNDAzMzM5LCJleHAiOjE3NTE0MDY5Mzl9.ZrLMDF-CpKeYvzLIn59OIoVzetQQlwCXTvcLICNfhUQ





####################################################################################################
########## USER ONLY
####################################################################################################

### Login do usuário com senha correta (usuário já existente no banco)
POST {{baseURL}}/user/public/login
Content-Type: application/json

{
    "email": "adopter_tron@ifrs.com.br",
    "password": "hash_tron"
}

### Criar uma nova adoção
POST {{baseURL}}/adoptions/protected/post
Content-Type: application/json
Authorization: Bearer {{adopter_Token_Ok}}

{
    "user_id": 20,
    "pet_id":  17
}





####################################################################################################
########## ADMIN ONLY
####################################################################################################

### Login do admin com senha correta (usuário já existente no banco)
POST {{baseURL}}/user/public/login
Content-Type: application/json

{
    "email": "admin1@ifrs.com.br",
    "password": "admin1_password"
}

### Listar todas adoções (rota protegida, requer token de usuário com role "admin")
GET {{baseURL}}/adoptions/protected/getAll
Accept: application/json
Authorization: Bearer {{admin_Token_Ok}}

### Listar todas adoções pelo ID (rota protegida, requer token de usuário com role "admin")
GET {{baseURL}}/adoptions/protected/getByID/9
Accept: application/json
Authorization: Bearer {{admin_Token_Ok}}