@baseURL = http://localhost:3000

@adopter_Token_Ok = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb3B0ZXJfMUBpZnJzLmVkdS5iciIsInJvbGUiOiJhZG9wdGVyIiwiaWF0IjoxNzUxMzM0NDg4LCJleHAiOjE3NTEzMzgwODh9.2PSO6XnAqrPBCRwFMqxbcZEs9EaSJypyPN1h5mCbq4k
@adopter_Token_Nok = WRONG_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb3B0ZXJfMUBpZnJzLmVkdS5iciIsInJvbGUiOiJhZG9wdGVyIiwiaWF0IjoxNzUxMzM0NDg4LCJleHAiOjE3NTEzMzgwODh9.2PSO6XnAqrPBCRwFMqxbcZEs9EaSJypyPN1h5mCbq4k

@admin_Token_Ok = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluXzFAaWZycy5lZHUuYnIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTEzMzQ2MTYsImV4cCI6MTc1MTMzODIxNn0.XGmIQSFwCQZWP29V5ogpl2ubvrANmoer-5TYyF6m9Ns
@admin_Token_Nok = WRONG_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluXzFAaWZycy5lZHUuYnIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTEzMzQ2MTYsImV4cCI6MTc1MTMzODIxNn0.XGmIQSFwCQZWP29V5ogpl2ubvrANmoer-5TYyF6m9Ns





####################################################################################################
########## USER ONLY
####################################################################################################

### Login do usuário com senha correta (usuário já existente no banco)
POST {{baseURL}}/user/public/login
Content-Type: application/json

{
    "email": "adopter_1@ifrs.edu.br",
    "password": "123456"
}

### Criar uma nova adoção
POST {{baseURL}}/adoptions/protected/post
Content-Type: application/json
Authorization: Bearer {{adopter_Token_Ok}}

{
    "user_id": 1,
    "pet_id": 1
}





####################################################################################################
########## ADMIN ONLY
####################################################################################################

### Login do admin com senha correta (usuário já existente no banco)
POST {{baseURL}}/user/public/login
Content-Type: application/json

{
    "email": "admin_1@ifrs.edu.br",
    "password": "admin123"
}

### Listar todas adoções (rota protegida, requer token de usuário com role "admin")
GET {{baseURL}}/adoptions/protected/getAll
Accept: application/json
Authorization: Bearer {{admin_Token_Ok}}

### Listar todas adoções pelo ID (rota protegida, requer token de usuário com role "admin")
GET {{baseURL}}/adoptions/protected/getByID/1
Accept: application/json
Authorization: Bearer {{admin_Token_Ok}}