@baseURL = http://localhost:3000

@adopter_Token_Ok = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb3B0ZXJfMUBpZnJzLmVkdS5iciIsInJvbGUiOiJhZG9wdGVyIiwiaWF0IjoxNzUxMzczODIyLCJleHAiOjE3NTEzNzc0MjJ9.37jspxnTocJMwN1aLQY2PMB5J4_XeE6vNKxkuIprNiY

@admin_Token_Ok = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbl8xQGlmcnMuZWR1LmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxMzkzMzQwLCJleHAiOjE3NTEzOTY5NDB9._931jhKg_8dwQK4wHQso6CyqApcCM-iKpwSDegOo6DQ





####################################################################################################
########## PUBLIC
####################################################################################################

### Listar os pets pelo STATUS
GET {{baseURL}}/pets/public/getByStatus/available
Accept: application/json





####################################################################################################
########## ADMIN ONLY
####################################################################################################

### Login do admin com senha correta (usuário já existente no banco)
POST {{baseURL}}/user/public/login
Content-Type: application/json

{
    "email": "admin_1@ifrs.edu.br",
    "password": "admin123"
}

### Listar todos os pets (rota protegida, requer token de usuário com role "admin")
GET {{baseURL}}/pets/protected/getAll
Accept: application/json
Authorization: Bearer {{admin_Token_Ok}}

### Listar os pets pelo ID (rota protegida, requer token de usuário com role "admin")
GET {{baseURL}}/pets/protected/getByID/10
Accept: application/json
Authorization: Bearer {{admin_Token_Ok}}

### Criar um novo pet (rota protegida, requer token de usuário com role "admin")
POST {{baseURL}}/pets/protected/post
Content-Type: application/json
Authorization: Bearer {{admin_Token_Ok}}

{
    "name": "Tron",
    "age": 10,
    "species": "virtual dog",
    "size": "big",
    "status": "available",
    "description": "fast"
}

### Atualizar um pet existente (rota protegida, requer token de usuário com role "admin")
PUT {{baseURL}}/pets/protected/update/10
Content-Type: application/json
Authorization: Bearer {{admin_Token_Ok}}

{
    "name": "Cluzinho",
    "age": 10,
    "species": "virtual dog",
    "size": "large",
    "status": "available",
    "description": "fast"
}

### Deletar um pet existente (rota protegida, requer token de usuário com role "admin")
DELETE {{baseURL}}/pets/protected/delete/1
Accept: application/json
Authorization: Bearer {{admin_Token_Ok}}