@baseURL = http://localhost:3000

@id_Pet_Get = 10
@id_Pet_Put = 3
@id_Pet_Delete = 3






### Listar todos os pets
GET {{baseURL}}/pets/public
Accept: application/json

### Listar os pets pelo ID
GET {{baseURL}}/pets/public/id/{{id_Pet_Get}}
Accept: application/json

### Listar os pets pelo status de disponiveis
GET {{baseURL}}/pets/public/status/available
Accept: application/json





### Criar um novo pet
POST {{baseURL}}/pets/public
Content-Type: application/json

{
    "name": "Tron",
    "age": 10,
    "species": "virtual dog",
    "size": "big",
    "status": "available",
    "description": "fast"
}





### Atualizar um pet existente (substitua @id_Pet_Put)
PUT {{baseURL}}/pets/public/update/{{id_Pet_Put}}
Content-Type: application/json

{
    "name": "Clu",
    "age": 10,
    "species": "virtual dog",
    "size": "large",
    "status": "available",
    "description": "fast"
}

### Atualizar pet inexistente (erro esperado)
PUT {{baseURL}}/pets/public/update/9999
Content-Type: application/json

{
    "name": "Tron",
    "age": 10,
    "species": "virtual dog",
    "size": "big",
    "status": "available",
    "description": "fast"
}





### Deletar um pet existente (substitua @id_Pet_Delete)
DELETE {{baseURL}}/pets/public/delete/{{id_Pet_Delete}}
Accept: application/json

### Deletar um pet inexistente (erro esperado)
DELETE {{baseURL}}/pets/public/delete/9999
Accept: application/json