@baseURL = http://localhost:3000

@adopter_Token_Ok = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb3B0ZXJfMUBpZnJzLmVkdS5iciIsInJvbGUiOiJhZG9wdGVyIiwiaWF0IjoxNzUxMjUxMDcwLCJleHAiOjE3NTEyNTQ2NzB9.C11GCRiO45TKZb55ZyxsXbY076OihtQAHntnyFc3y0o
@adopter_Token_Nok = WRONG_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb3B0ZXJfMUBpZnJzLmVkdS5iciIsInJvbGUiOiJhZG9wdGVyIiwiaWF0IjoxNzUxMjUxMDcwLCJleHAiOjE3NTEyNTQ2NzB9.C11GCRiO45TKZb55ZyxsXbY076OihtQAHntnyFc3y0o

@admin_Token_Ok = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluXzFAaWZycy5lZHUuYnIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTEzMzQ2MTYsImV4cCI6MTc1MTMzODIxNn0.XGmIQSFwCQZWP29V5ogpl2ubvrANmoer-5TYyF6m9Ns
@admin_Token_Nok = WRONG_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluXzFAaWZycy5lZHUuYnIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTEzMzQ2MTYsImV4cCI6MTc1MTMzODIxNn0.XGmIQSFwCQZWP29V5ogpl2ubvrANmoer-5TYyF6m9Ns





####################################################################################################
########## ADMIN ONLY
####################################################################################################

### Login do usuário com senha correta (usuário já existente no banco)
POST {{baseURL}}/user/public/login
Content-Type: application/json

{
    "email": "adopter_1@ifrs.edu.br",
    "password": "123456"
}

### Listar todos os pets (rota protegida, requer token de usuário com role "admin")
GET {{baseURL}}/pets/protected/getAll
Accept: application/json
Authorization: Bearer {{admin_Token_Ok}}

### Listar os pets pelo ID (rota protegida, requer token de usuário com role "admin")
GET {{baseURL}}/pets/protected/getByID/1
Accept: application/json
Authorization: Bearer {{admin_Token_Ok}}

### Criar um novo pet (rota protegida, requer token de usuário com role "admin")
POST {{baseURL}}/pets/protected/post
Content-Type: application/json
Authorization: Bearer {{admin_Token_Ok}}

{
    "name": "Tron",
    "age": 10,
    "species": "virtual dog",
    "size": "big",
    "status": "available",
    "description": "fast"
}

### Atualizar um pet existente (rota protegida, requer token de usuário com role "admin")
PUT {{baseURL}}/pets/protected/update/8
Content-Type: application/json
Authorization: Bearer {{admin_Token_Ok}}

{
    "name": "Clu",
    "age": 10,
    "species": "virtual dog",
    "size": "large",
    "status": "available",
    "description": "fast"
}

### Deletar um pet existente (rota protegida, requer token de usuário com role "admin")
DELETE {{baseURL}}/pets/protected/delete/8
Accept: application/json
Authorization: Bearer {{admin_Token_Ok}}